services:
  traefik:
    image: traefik:v3.0
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"         
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  book-service:
    build: ./app
    container_name: book-service
    command: opentelemetry-instrument uvicorn main:app --app-dir /app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app:cached
    ports:
      - "8000:8000"
    depends_on:
      - kafka
      - db
      - redis
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      DATABASE_URL: postgresql+asyncpg://myuser:mypassword@db:5432/mydatabase
      PYTHONPATH: /app
      PYTHONUNBUFFERED: "1"
      OTEL_SERVICE_NAME: book-service
      OTEL_TRACES_EXPORTER: zipkin
      OTEL_EXPORTER_ZIPKIN_ENDPOINT: http://zipkin:9411/api/v2/spans
      OTEL_METRICS_EXPORTER: "none"
    restart: on-failure
    labels:
      - "traefik.enable=true"
      # роутер: все запросы на / идут в book-service
      - "traefik.http.routers.gateway.rule=PathPrefix(`/`)"
      - "traefik.http.routers.gateway.entrypoints=web"
      # говорим Traefik, какой порт внутри контейнера слушает сервис
      - "traefik.http.services.book-gateway.loadbalancer.server.port=8000"
    
    
  
  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    restart: always

  mongodb:
    image: mongo:6
    container_name: mongo_db
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo_data:/data/db
  
  rabbbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_broker
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always

  order-worker:
    build: ./app
    container_name: order-worker
    command: celery -A delayed_tasks.worker_service.celery_app worker --loglevel=info
    depends_on:
      - rabbbitmq
    environment:
      CELERY_BROKER_URL: amqp://guest:guest@rabbbitmq:5672//
      CELERY_RESULT_BACKEND: rpc://
    restart: always
  gateway:
    build: ./gateway
    container_name: api_gateway
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    depends_on:
      - book-service
    ports:
      - "8001:8000"
    environment:
      BOOK_SERVICE_URL: http://book-service:8000
      JWT_SECRET_KEY: secretexample
      JWT_ALGORITHM: HS256
    restart: always

  celery_beat:
    build: ./app
    container_name: celery_beat
    command: opentelemetry-instrument celery -A delayed_tasks.worker_service.celery_app beat --loglevel=info
    depends_on:
      - rabbbitmq
    environment:
      CELERY_BROKER_URL: amqp://guest:guest@rabbbitmq:5672//
      CELERY_RESULT_BACKEND: rpc://

      OTEL_SERVICE_NAME: order-worker
      OTEL_TRACES_EXPORTER: zipkin
      OTEL_EXPORTER_ZIPKIN_ENDPOINT: http://zipkin:9411/api/v2/spans
      OTEL_METRICS_EXPORTER: "none"
    restart: always
  
  flower:
    build: ./app
    container_name: celery_flower
    command: celery -A delayed_tasks.worker_service.celery_app flower --address=0.0.0.0 --port=5555
    depends_on:
      - rabbbitmq
    ports:
      - "5555:5555"
    environment:
      CELERY_BROKER_URL: amqp://guest:guest@rabbbitmq:5672//
      CELERY_RESULT_BACKEND: rpc://
    restart: always
  
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

  analytics-worker:
    build: ./app
    command: bash -c "sleep 45 && python -m kafka_client.analitics_worker_runner"
    depends_on:
      - kafka
      - mongodb

  faust_analytics:
    build: ./app
    command: bash -c "sleep 45 && faust -A faust_analytics worker -l info"
    depends_on:
      - kafka
    restart: always

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
  
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    depends_on:
      - gateway
      - book-service
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    volumes:
      - ./monitoring/loki-config.yml:/etc/loki/local-config.yaml
    restart: always

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    command: -config.file=/etc/promtail/promtail-config.yml
    volumes:
      - ./monitoring/promtail-config.yml:/etc/promtail/promtail-config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - loki
    restart: always

volumes:
  postgres_data:
  mongo_data:
  grafana_data: