# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'app.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapp.proto\x12\x03\x61pp\"\x1b\n\rAuthorRequest\x12\n\n\x02id\x18\x01 \x01(\x05\":\n\x0b\x41uthorReply\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tbiography\x18\x03 \x01(\t\"\x07\n\x05\x45mpty2q\n\rAuthorService\x12\x31\n\tGetAuthor\x12\x12.app.AuthorRequest\x1a\x10.app.AuthorReply\x12-\n\x0bListAuthors\x12\n.app.Empty\x1a\x10.app.AuthorReply0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUTHORREQUEST']._serialized_start=18
  _globals['_AUTHORREQUEST']._serialized_end=45
  _globals['_AUTHORREPLY']._serialized_start=47
  _globals['_AUTHORREPLY']._serialized_end=105
  _globals['_EMPTY']._serialized_start=107
  _globals['_EMPTY']._serialized_end=114
  _globals['_AUTHORSERVICE']._serialized_start=116
  _globals['_AUTHORSERVICE']._serialized_end=229
# @@protoc_insertion_point(module_scope)
