apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fastapi
  namespace: monitoring
  labels:
    release: monitoring        
spec:
  namespaceSelector:
    matchNames: ["default"]
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: ["gateway","book-service"]   
  endpoints:
    - port: http               
      path: /metrics
      interval: 15s
      scrapeTimeout: 5s